# Generated by Django 5.2 on 2025-05-01 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_eliteestateroyce'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eliteestateroyce',
            options={},
        ),
    ]
